version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.33.3
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - "prometheus-pushgateway"
  
  prometheus-pushgateway:
    image: prom/pushgateway
    restart: always
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana:9.1.0
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - "prometheus"
